# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gamehall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.IntegerField(null=True)),
                ('room_num', models.CharField(max_length=4, null=True)),
                ('player_num', models.CharField(max_length=2, null=True)),
                ('role', models.CharField(max_length=6, null=True)),
                ('player', models.CharField(max_length=16, null=True)),
                ('person_id', models.CharField(max_length=40, null=True)),
                ('time', models.TimeField(auto_now=True)),
            ],
        ),
    ]
