# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wolfkill', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamehall',
            name='player',
            field=models.CharField(default='还没加入', max_length=16),
        ),
    ]
